// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: service/rfqmm/api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RfqMmApiClient is the client API for RfqMmApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RfqMmApiClient interface {
	Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
}

type rfqMmApiClient struct {
	cc grpc.ClientConnInterface
}

func NewRfqMmApiClient(cc grpc.ClientConnInterface) RfqMmApiClient {
	return &rfqMmApiClient{cc}
}

func (c *rfqMmApiClient) Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/service.rfqmm.RfqMmApi/Price", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfqMmApiClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/service.rfqmm.RfqMmApi/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RfqMmApiServer is the server API for RfqMmApi service.
// All implementations should embed UnimplementedRfqMmApiServer
// for forward compatibility
type RfqMmApiServer interface {
	Price(context.Context, *PriceRequest) (*PriceResponse, error)
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
}

// UnimplementedRfqMmApiServer should be embedded to have forward compatible implementations.
type UnimplementedRfqMmApiServer struct {
}

func (UnimplementedRfqMmApiServer) Price(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Price not implemented")
}
func (UnimplementedRfqMmApiServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}

// UnsafeRfqMmApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RfqMmApiServer will
// result in compilation errors.
type UnsafeRfqMmApiServer interface {
	mustEmbedUnimplementedRfqMmApiServer()
}

func RegisterRfqMmApiServer(s grpc.ServiceRegistrar, srv RfqMmApiServer) {
	s.RegisterService(&RfqMmApi_ServiceDesc, srv)
}

func _RfqMmApi_Price_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfqMmApiServer).Price(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.rfqmm.RfqMmApi/Price",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfqMmApiServer).Price(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfqMmApi_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfqMmApiServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.rfqmm.RfqMmApi/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfqMmApiServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RfqMmApi_ServiceDesc is the grpc.ServiceDesc for RfqMmApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RfqMmApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.rfqmm.RfqMmApi",
	HandlerType: (*RfqMmApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Price",
			Handler:    _RfqMmApi_Price_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _RfqMmApi_Quote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/rfqmm/api.proto",
}
